language: node_js
sudo: false
node_js:
  - "7"

install:
- yarn install

script:
- yarn test:cov

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true